import './globals.css'

// ** Import Components
import Header from './components/Header'

export const metadata = {
  title: 'Sotota Stall',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Header/>
      <body>{children}</body>
    </html>
  )
}
