import './globals.css'

// ** Import Components
import Header from './components/Header';
import Footer from './components/Footer';
import Cart from "./elements/Cart"

//** Swiper Slider
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";


export const metadata = {
  title: 'Sotota Stall',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
        <Footer/>
        <Cart/>
      </body>
    </html>
  )
}
