import "rc-slider/assets/index.css";
import "./globals.css";

// ** int18n
import { useLocale } from "next-intl";
import { notFound } from "next/navigation";

// ** Import Components
import Footer from "@/components/footer/Footer";
import Cart from "@/components/elements/Cart";
import CheckConnection from "@/components/CheckConnection";
import Header from "@/components/navbar/Header";
import NavItems from "@/components/navbar/NavItems";

//** Swiper Slider
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";

export const metadata = {
  title: "Sotota Stall",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  const locale = useLocale();

  // Show a 404 error if the user requests an unknown locale
  if (params.locale !== locale) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body>
        <Header locale={locale}>
          <NavItems />
        </Header>
        <CheckConnection>{children}</CheckConnection>
        <Footer />
        <Cart />
      </body>
    </html>
  );
}
